# Pipeline configuration for BlackGEM variable source classification via machine learning.

data_root = /data/dir

project_id = /project/id/for/Google/cloud/storage

variable_table = /path/to/Google/Cloud/database/file

bg_detections_table = /path/to/Google/Cloud/database/file

bg_images_table = /path/to/Google/Cloud/database/file

wd_table = /path/to/WD/catalogue

hr_table = /path/to/HR/catalogue